// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonellerUoW.Models.Entities;

namespace PersonellerUoW.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211016211912_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonellerUoW.Models.Entities.Cografya", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UstID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cografyas");
                });

            modelBuilder.Entity("PersonellerUoW.Models.Entities.Medya", b =>
                {
                    b.Property<int>("MediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MediaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaID");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("PersonellerUoW.Models.Entities.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<int?>("MediaID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonelID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("MediaID");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("PersonellerUoW.Models.Entities.Personel", b =>
                {
                    b.HasOne("PersonellerUoW.Models.Entities.Cografya", "City")
                        .WithMany()
                        .HasForeignKey("CityID");

                    b.HasOne("PersonellerUoW.Models.Entities.Cografya", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("PersonellerUoW.Models.Entities.Medya", "Media")
                        .WithMany()
                        .HasForeignKey("MediaID");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
